# Generated by Django 5.2.5 on 2025-09-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useraccount_auth_provider_alter_useraccount_password'),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.sessionstore', to_field='session_id'),
        ),
        migrations.AlterField(
            model_name='userfact',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='authentication.sessionstore', to_field='session_id'),
        ),
    ]
