# Generated by Django 5.2.5 on 2025-09-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatmessage_session_alter_userfact_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userfact',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
