# Generated by Django 5.2.5 on 2025-09-04 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useraccount_auth_provider_alter_useraccount_password'),
        ('chatbot', '0006_chatentry_uploadedimage_delete_usermemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.useraccount'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.useraccount'),
        ),
    ]
