# Generated by Django 5.2.5 on 2025-09-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_chatentry_user_alter_uploadedimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatEntry',
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
