# Generated by Django 5.2.5 on 2025-09-05 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_chatmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(default=datetime.datetime(2025, 9, 5, 18, 19, 57, 531559, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
