# Generated by Django 5.2.5 on 2025-09-05 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_chatmessage_image_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='image_description',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(default=datetime.datetime(2025, 9, 5, 18, 39, 8, 27967, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(default=datetime.datetime(2025, 9, 5, 18, 39, 12, 236275, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
