# Generated by Django 5.2.5 on 2025-09-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_chatsession_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='memory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
