# Generated by Django 5.2.5 on 2025-09-05 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useraccount_auth_provider_alter_useraccount_password'),
        ('chatbot', '0014_chatsession_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('data_type', models.CharField(default='string', max_length=50)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('source_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='authentication.useraccount')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'key'], name='chatbot_use_user_id_4d67aa_idx')],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
