# Generated by Django 5.2.5 on 2025-09-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_useraccount_auth_provider_alter_useraccount_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCOSInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_length', models.CharField(blank=True, max_length=50)),
                ('last_period_date', models.DateField(blank=True, null=True)),
                ('pcos_status', models.CharField(max_length=50)),
                ('mood_stress', models.CharField(max_length=50)),
                ('goal', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.useraccount')),
            ],
        ),
    ]
