# Generated by Django 5.2.5 on 2025-09-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_pcosuserinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PCOSInfo',
        ),
    ]
