# Generated by Django 5.2.5 on 2025-09-03 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_delete_pcosinfo'),
        ('authentication', '0002_useraccount_auth_provider_alter_useraccount_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCOSUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_length', models.CharField(blank=True, max_length=50, null=True)),
                ('last_period_date', models.DateField(blank=True, null=True)),
                ('pcos_status', models.CharField(blank=True, max_length=50, null=True)),
                ('mood', models.CharField(blank=True, max_length=50, null=True)),
                ('stress_level', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis_length', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_concerns', models.TextField(blank=True, null=True)),
                ('diet_description', models.TextField(blank=True, null=True)),
                ('activity_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('support_needed', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.useraccount')),
            ],
        ),
    ]
