# Generated by Django 5.2.5 on 2025-09-03 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_pcosuserdata'),
        ('authentication', '0002_useraccount_auth_provider_alter_useraccount_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcosuserdata',
            options={'verbose_name': 'PCOS User Data', 'verbose_name_plural': 'PCOS User Data'},
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.useraccount', unique=True),
        ),
    ]
