# Generated by Django 5.2.5 on 2025-10-20 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_alter_pcosuserdata_options_and_more'),
        ('authentication', '0002_useraccount_auth_provider_alter_useraccount_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('guide', 'Guide'), ('infographic', 'Infographic'), ('research', 'Research Paper')], max_length=50)),
                ('category', models.CharField(choices=[('basics', 'PCOS Basics'), ('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('mental_health', 'Mental Health'), ('fertility', 'Fertility'), ('treatment', 'Treatment Options'), ('lifestyle', 'Lifestyle Management')], max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='pcosuserdata',
            options={'ordering': ['-updated_at'], 'verbose_name': 'PCOS User Data', 'verbose_name_plural': 'PCOS User Data'},
        ),
        migrations.AddField(
            model_name='pcosuserdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time data was updated'),
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='activity_frequency',
            field=models.CharField(blank=True, help_text='Physical activity frequency', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When onboarding was completed'),
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='cycle_length',
            field=models.CharField(blank=True, help_text='Average cycle length in days or description', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='diagnosis_length',
            field=models.CharField(blank=True, help_text='How long user has been diagnosed', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='diet_description',
            field=models.TextField(blank=True, help_text='Current diet and eating habits', null=True),
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='last_period_date',
            field=models.DateField(blank=True, help_text='First day of last menstrual period', null=True),
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='mood',
            field=models.CharField(blank=True, help_text='Current mood state', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='pcos_status',
            field=models.CharField(blank=True, help_text='Current PCOS management status', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='primary_concerns',
            field=models.TextField(blank=True, help_text='Main PCOS-related concerns', null=True),
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='stress_level',
            field=models.CharField(blank=True, help_text='Current stress level', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='support_needed',
            field=models.TextField(blank=True, help_text='Type of support user is seeking', null=True),
        ),
        migrations.AlterField(
            model_name='pcosuserdata',
            name='user',
            field=models.OneToOneField(help_text='User this PCOS data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pcos_data', to='authentication.useraccount'),
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Discussion'), ('success', 'Success Stories'), ('nutrition', 'Nutrition & Diet'), ('exercise', 'Exercise & Fitness'), ('mental_health', 'Mental Health'), ('symptoms', 'Symptoms & Management'), ('questions', 'Questions & Advice')], default='general', max_length=50)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='authentication.useraccount')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('likes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='authentication.useraccount')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auth_user.communitypost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength Training'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('hiit', 'HIIT'), ('walking', 'Walking'), ('swimming', 'Swimming'), ('cycling', 'Cycling')], max_length=50)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('instructions', models.TextField()),
                ('benefits', models.TextField(help_text='PCOS-specific benefits')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_plans', to='authentication.useraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('ingredients', models.TextField(help_text='Comma-separated ingredients')),
                ('instructions', models.TextField()),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('carbs', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('fats', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('is_pcos_friendly', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='authentication.useraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('reminder', 'Reminder'), ('achievement', 'Achievement'), ('community', 'Community Update'), ('health', 'Health Tip'), ('cycle', 'Cycle Update'), ('general', 'General')], default='general', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.useraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cramps', models.IntegerField(default=0, help_text='Pain level 0-10')),
                ('bloating', models.IntegerField(default=0, help_text='Bloating level 0-10')),
                ('acne', models.BooleanField(default=False)),
                ('hair_loss', models.BooleanField(default=False)),
                ('energy_level', models.IntegerField(default=5, help_text='Energy level 0-10')),
                ('mood_score', models.IntegerField(default=5, help_text='Mood score 0-10')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to='authentication.useraccount')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('cycle_reminders', models.BooleanField(default=True)),
                ('daily_tips', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='private', max_length=20)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('data_sharing', models.BooleanField(default=False, help_text='Share anonymized data for research')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='authentication.useraccount')),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='WellnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal_type', models.CharField(choices=[('weight', 'Weight Management'), ('exercise', 'Exercise Consistency'), ('nutrition', 'Nutrition Improvement'), ('sleep', 'Better Sleep'), ('stress', 'Stress Reduction'), ('cycle', 'Cycle Regularity'), ('custom', 'Custom Goal')], max_length=50)),
                ('target_value', models.CharField(help_text='Target to achieve', max_length=100)),
                ('current_value', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('target_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_goals', to='authentication.useraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PCOSUserInfo',
        ),
    ]
