# Generated by Django 5.2.5 on 2025-10-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0006_resource_alter_pcosuserdata_options_and_more'),
        ('authentication', '0002_useraccount_auth_provider_alter_useraccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['-created_at'], name='auth_user_c_created_068ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['category', '-created_at'], name='auth_user_c_categor_1e15f4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='auth_user_n_user_id_9ecb78_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='auth_user_n_user_id_15fdb8_idx'),
        ),
        migrations.AddIndex(
            model_name='symptomlog',
            index=models.Index(fields=['user', '-date'], name='auth_user_s_user_id_2336f1_idx'),
        ),
        migrations.AddIndex(
            model_name='symptomlog',
            index=models.Index(fields=['date'], name='auth_user_s_date_6e3f93_idx'),
        ),
    ]
