# Generated by Django 5.2.5 on 2025-10-20 21:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_symptomlog_updated_at_and_more'),
        ('authentication', '0002_useraccount_auth_provider_alter_useraccount_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterIntakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('glasses', models.IntegerField(default=0, help_text='Number of glasses (8oz each) consumed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='authentication.useraccount')),
            ],
            options={
                'verbose_name': 'Water Intake Log',
                'verbose_name_plural': 'Water Intake Logs',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='auth_user_w_user_id_8f34f0_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
